# Generated by Django 5.2.4 on 2025-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lockers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
