# Generated by Django 5.2.4 on 2025-08-06 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lockers", "0002_student_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locker_number", models.CharField(max_length=10, unique=True)),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "booked_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
