# Generated by Django 5.2.4 on 2025-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lockers", "0004_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="locker",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
