# Generated by Django 5.2.4 on 2025-08-13 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lockers", "0006_lockeraccessotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="LockerRentalArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("was_overdue", models.BooleanField(default=False)),
                (
                    "fine_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "locker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lockers.locker"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LockerReturnLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("returned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lockers.locker"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
