# Generated by Django 5.2.4 on 2025-08-13 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lockers", "0007_lockerrentalarchive_lockerreturnlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booked_at",
        ),
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="locker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lockers.locker"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
