# Generated by Django 5.2.4 on 2025-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lockers", "0009_lockeraccesslog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lockerrentalarchive",
            old_name="booked_at",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="lockerrentalarchive",
            old_name="was_overdue",
            new_name="overdue",
        ),
        migrations.RenameField(
            model_name="lockerrentalarchive",
            old_name="ended_at",
            new_name="start_time",
        ),
        migrations.RemoveField(
            model_name="lockerrentalarchive",
            name="fine_amount",
        ),
        migrations.AddField(
            model_name="lockerrentalarchive",
            name="fine",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
