# Generated by Django 5.2.4 on 2025-08-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lockers", "0010_rename_booked_at_lockerrentalarchive_end_time_and_more"),
        ("lockers", "0011_seed_lockers"),
    ]

    operations = []
